sudo: required
language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
- ls
- docker build -t ciui .
- docker run -d -p 8080:8080 --name app ciui
- docker ps -a

script:
- docker exec app npm test

after_script:
- docker rm -f app
