---
kind: Template
apiVersion: v1
metadata:
  name: ci-pipeline-ui
  annotations:
    openshift.io/display-name: ci-pipeline-ui
    description: ci-pipeline-ui deployed on openshift
    tags: ci-pipeline-ui,nodejs
    iconClass: icon-nodejs
    openshift.io/long-description: This template defines resources needed to develop
      ci-pipeline-ui including a build configuration and application deployment configuration.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/documentation-url: https://github.com/samvarankashyap/ci-pipeline-ui
    openshift.io/support-url: https://access.redhat.com
message: |-
  The following service(s) have been created in your project: ${NAME}.
  For more information about using this template, including OpenShift considerations, see https://github.com/openshift/nodejs-ex/blob/master/README.md.
labels:
  template: ci-pipeline-ui
  app: ci-pipeline-ui
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "ci-ui-web"
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: "${NAME}"
- kind: Service
  apiVersion: v1
  metadata:
    name: "ci-ui-rest"
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: rest
      port: 3000
      targetPort: 3000
    selector:
      name: "${NAME}"
- kind: Route
  apiVersion: v1
  metadata:
    name: "ci-ui-web"
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: "ci-ui-web"
- kind: Route
  apiVersion: v1
  metadata:
    name: "ci-ui-rest"
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: "ci-ui-rest"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ci-pipeline-ui
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ci-pipeline-ui:latest
    resources: {}
    source:
      contextDir: "${REPO_CONTEXTDIR}"
      git:
        ref: "${REPO_REF}"
        uri: "${REPO_URL}"
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
        env:
        - name: CONTAINER_NAME
          value: ci-pipeline-ui
        - name: APP_DOMAIN
          value: "${APPLICATION_DOMAIN}"
      type: Docker
    triggers:
    - type: ConfigChange
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: 'true'
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ci-pipeline-ui
        from:
          kind: ImageStreamTag
          name: "${NAME}:latest"
    - type: ConfigChange
    replicas: 1
    selector:
      name: "${NAME}"
    template:
      metadata:
        name: "${NAME}"
        labels:
          name: "${NAME}"
      spec:
        containers:
        - name: ci-pipeline-ui
          image: "${NAME}:latest"
          ports:
          - containerPort: 8080
          - containerPort: 3000
          readinessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 3
            httpGet:
              path: "/"
              port: 8080
          livenessProbe:
            timeoutSeconds: 3
            initialDelaySeconds: 30
            httpGet:
              path: "/"
              port: 8080
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          env:
            - name: OS_DOMAIN
              value: "${OPENSHIFT_DOMAIN_NAME}"
            - name: APP_DOMAIN
              value: "${APPLICATION_DOMAIN}"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the frontend objects defined in this template.
  required: true
  value: ci-pipeline-ui
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  required: true
  value: testproject
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  required: true
  value: 512Mi
- name: REPO_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  required: true
  value: https://github.com/samvarankashyap/ci-pipeline-ui.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
- name: REPO_CONTEXTDIR
  displayName: Context Directory
  description: Set this to the relative path to your project if it is not in the root
    of your repository.
- name: REPO_REF
  displayName: Git Reference
  description: The git ref or tag to use for customization.
  value: master
- name: APPLICATION_DOMAIN
  displayName: Application Hostname
  description: The exposed hostname that will route to the Node.js service, if left
    blank a value will be defaulted.
  value: ''
- name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: Github trigger secret.  A difficult to guess string encoded as part
    of the webhook URL.  Not encrypted.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: GENERIC_WEBHOOK_SECRET
  displayName: Generic Webhook Secret
  description: A secret string used to configure the Generic webhook.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
- name: NPM_MIRROR
  displayName: Custom NPM Mirror URL
  description: The custom NPM mirror URL
  value: ''
- name: OPENSHIFT_DOMAIN_NAME
  displayName: Openshift domain for external routing
  description: openshift domain necessary for external routing for minishift 192.168.x.x.nip.io
  value: '192.168.42.114.nip.io'
