apiVersion: v1
kind: Template
labels:
  template: ci-pipeline-ui-builder
metadata:
  annotations:
    description: ci-pipeline-ui-builder
    iconClass: ci-pipeline-ui
    tags: instant-app
  name: ci-pipeline-ui-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: ci-pipeline-ui
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ci-pipeline-ui
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ci-pipeline-ui:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
        env:
          - name: CONTAINER_NAME
            value: ci-pipeline-ui
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/samvarankashyap/ci-pipeline-ui.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: /
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
